# Generated by Django 3.1.3 on 2024-10-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20241008_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='title',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_product_ref', to='auctions.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_product_ref', to='auctions.product'),
        ),
    ]
