# Generated by Django 3.1.3 on 2024-10-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20241011_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_ref', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_ref', to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
