# Generated by Django 3.1.3 on 2024-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20241011_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='pictures/default.jpeg', upload_to='pictures/'),
        ),
    ]
