# Generated by Django 3.1.3 on 2024-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
