# Generated by Django 3.1.3 on 2024-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='comment_auction_ref', to='auctions.AuctionListing'),
        ),
    ]
