# Generated by Django 3.1.3 on 2024-10-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20241018_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auction',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_auction_ref', to='auctions.Comment'),
        ),
    ]
